// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeapp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmT5b_7eqvVGMaaUe1HMcwZtyrqe5eAxg',
    appId: '1:674385556656:web:367ab2d7e46b7e42d1f775',
    messagingSenderId: '674385556656',
    projectId: 'fir-app-8c8a6',
    authDomain: 'fir-app-8c8a6.firebaseapp.com',
    storageBucket: 'fir-app-8c8a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhD4mlvKsWoMs7lxWp7s3P0zr00AmOAb0',
    appId: '1:674385556656:android:52006e61e73fc1c1d1f775',
    messagingSenderId: '674385556656',
    projectId: 'fir-app-8c8a6',
    storageBucket: 'fir-app-8c8a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhQuF9T_hEGMAvUhixFWpdCm4183uccHs',
    appId: '1:674385556656:ios:a75992703fb5be6fd1f775',
    messagingSenderId: '674385556656',
    projectId: 'fir-app-8c8a6',
    storageBucket: 'fir-app-8c8a6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhQuF9T_hEGMAvUhixFWpdCm4183uccHs',
    appId: '1:674385556656:ios:a75992703fb5be6fd1f775',
    messagingSenderId: '674385556656',
    projectId: 'fir-app-8c8a6',
    storageBucket: 'fir-app-8c8a6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmT5b_7eqvVGMaaUe1HMcwZtyrqe5eAxg',
    appId: '1:674385556656:web:abf1c9fc7108971ad1f775',
    messagingSenderId: '674385556656',
    projectId: 'fir-app-8c8a6',
    authDomain: 'fir-app-8c8a6.firebaseapp.com',
    storageBucket: 'fir-app-8c8a6.firebasestorage.app',
  );
}
